### ISSUE TITLE
Create the "Next matches" and "Results" modals

### ISSUE THREAD

**Issue by thierrymgn** [wanned/karmine-corp-app#18]
**Design**

Use the old calendar design for both modals. The modal should be above the navbar (we could not view the navbar). Add a "Back" button.

**To-do**
- [x] Add the "Results" modal (use the `useResults` hook)
- [x] Add the "Next matches" modal (use the `useNextMacthes` hook)
- [x] Open the modals when clicking the corresponding button in the homepage
