### ISSUE TITLE
Create the settings page

### ISSUE THREAD

**Issue by arthur-fontaine** [wanned/karmine-corp-app#6]
Add a `SettingsContext` at the root of the app. The settings page will edit the states in the `SettingsContext`. The other pages  will be able to retrieve these settings.

**Tasks**
- [x] Create the `SettingsContext`
- [x] Create the `useSettings` hook
- [x] Create the settings page
